name: LateX CV to PDF

on:
  push:
    branches: 
      - master
      - develop
  pull_request:
    branches: [ master ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        id: compile-latex-document
        uses: ./
      - name: Upload CV in PDF to the workflow tab
        id: upload-workflow-tab
        uses: actions/upload-artifact@v2
        with:
          name: cv
          path: cv/cv.pdf
      - name: Create Release
        id: create-release
        if: github.ref == 'ref/head/master'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release CV
        id: upload-release-asset
        if: github.ref == 'ref/head/master'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: cv/cv.pdf
          asset_name: cv.pdf
          asset_content_type: application/pdf
